### ISSUE TITLE
java.io.IOException: null

### ISSUE THREAD

**Issue by inenashev** [TinkoffCreditSystems/gatling-amqp-plugin#9]
Hi, getting errors like this then trying to push message to the rabbitmq, 
logs say that
`21:00:24.685 [GatlingSystem-akka.actor.default-dispatcher-4] DEBUG ru.tinkoff.gatling.amqp.action.Publish - Message sent user=1 AMQPMessageID=some_id`
and then:
`Simulation amqp completed in 0 seconds
21:00:59.797 [GatlingSystem-akka.actor.default-dispatcher-4] ERROR ru.tinkoff.gatling.amqp.action.Publish - 'amqpPublish-2' crashed on session Session(amqp_vcrt,1,1598464859660,Map(68b63433-52a4-4471-aada-832a039db4af -> 0),0,OK,List(ExitOnCompleteLoopBlock(68b63433-52a4-4471-aada-832a039db4af)),io.gatling.core.protocol.ProtocolComponentsRegistry$$Lambda$447/0x0000000800f3a840@1b7e288a), forwarding to the next one
java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:129)
  | => aat com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:125)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:147)
	at com.rabbitmq.client.impl.ChannelN.open(ChannelN.java:133)
	at com.rabbitmq.client.impl.ChannelManager.createChannel(ChannelManager.java:182)
	at com.rabbitmq.client.impl.AMQConnection.createChannel(AMQConnection.java:555)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.createChannel(AutorecoveringConnection.java:165)
	at ru.tinkoff.gatling.amqp.client.AmqpChannelFactory.create(AmqpChannelFactory.scala:8)
	at ru.tinkoff.gatling.amqp.client.AmqpChannelFactory.create(AmqpChannelFactory.scala:7)
	at org.apache.commons.pool2.BasePooledObjectFactory.makeObject(BasePooledObjectFactory.java:58)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at ru.tinkoff.gatling.amqp.client.AmqpConnectionPool.channel(AmqpConnectionPool.scala:29)
	at ru.tinkoff.gatling.amqp.client.WithAmqpChannel.withChannel(WithAmqpChannel.scala:8)
	at ru.tinkoff.gatling.amqp.client.WithAmqpChannel.withChannel$(WithAmqpChannel.scala:7)
	at ru.tinkoff.gatling.amqp.client.AmqpPublisher.withChannel(AmqpPublisher.scala:11)
	at ru.tinkoff.gatling.amqp.client.AmqpPublisher.$anonfun$publish$2(AmqpPublisher.scala:21)
	at ru.tinkoff.gatling.amqp.client.AmqpPublisher.$anonfun$publish$2$adapted(AmqpPublisher.scala:20)
	at io.gatling.commons.validation.Success.onSuccess(Validation.scala:49)
	at io.gatling.commons.validation.Validation.foreach(Validation.scala:35)
	at io.gatling.commons.validation.Validation.foreach$(Validation.scala:35)
	at io.gatling.commons.validation.Success.foreach(Validation.scala:44)
	at ru.tinkoff.gatling.amqp.client.AmqpPublisher.$anonfun$publish$1(AmqpPublisher.scala:20)
	at ru.tinkoff.gatling.amqp.client.AmqpPublisher.$anonfun$publish$1$adapted(AmqpPublisher.scala:19)
	at io.gatling.commons.validation.Success.onSuccess(Validation.scala:49)
	at io.gatling.commons.validation.Validation.foreach(Validation.scala:35)
	at io.gatling.commons.validation.Validation.foreach$(Validation.scala:35)
	at io.gatling.commons.validation.Success.foreach(Validation.scala:44)
	at ru.tinkoff.gatling.amqp.client.AmqpPublisher.publish(AmqpPublisher.scala:19)
	at ru.tinkoff.gatling.amqp.action.AmqpAction.$anonfun$sendRequest$4(AmqpAction.scala:36)
	at ru.tinkoff.gatling.amqp.action.AmqpAction.$anonfun$sendRequest$4$adapted(AmqpAction.scala:28)
	at io.gatling.commons.validation.Success.map(Validation.scala:45)
	at ru.tinkoff.gatling.amqp.action.AmqpAction.$anonfun$sendRequest$3(AmqpAction.scala:28)
	at io.gatling.commons.validation.Success.flatMap(Validation.scala:46)
	at ru.tinkoff.gatling.amqp.action.AmqpAction.$anonfun$sendRequest$1(AmqpAction.scala:25)
	at io.gatling.commons.validation.Success.flatMap(Validation.scala:46)
	at ru.tinkoff.gatling.amqp.action.AmqpAction.sendRequest(AmqpAction.scala:24)
	at io.gatling.core.action.RequestAction.$anonfun$execute$1(Action.scala:100)
	at io.gatling.commons.validation.Success.flatMap(Validation.scala:46)
	at io.gatling.core.action.RequestAction.execute(Action.scala:97)
	at io.gatling.core.action.RequestAction.execute$(Action.scala:96)
	at ru.tinkoff.gatling.amqp.action.AmqpAction.execute(AmqpAction.scala:12)
	at io.gatling.core.action.Action.$bang(Action.scala:38)
	at io.gatling.core.action.Action.$bang$(Action.scala:38)
	at ru.tinkoff.gatling.amqp.action.AmqpAction.io$gatling$core$action$ChainableAction$$super$$bang(AmqpAction.scala:12)
	at io.gatling.core.action.ChainableAction.$bang(Action.scala:63)
	at io.gatling.core.action.ChainableAction.$bang$(Action.scala:61)
	at ru.tinkoff.gatling.amqp.action.AmqpAction.io$gatling$core$action$ExitableAction$$super$$bang(AmqpAction.scala:12)
	at io.gatling.core.action.ExitableAction.$bang(BlockExit.scala:141)
	at io.gatling.core.action.ExitableAction.$bang$(BlockExit.scala:139)
	at ru.tinkoff.gatling.amqp.action.AmqpAction.$bang(AmqpAction.scala:12)
	at io.gatling.core.action.InnerLoop.execute(Loop.scala:94)
	at io.gatling.core.action.Action.$bang(Action.scala:38)
	at io.gatling.core.action.Action.$bang$(Action.scala:38)
	at io.gatling.core.action.InnerLoop.io$gatling$core$action$ChainableAction$$super$$bang(Loop.scala:58)
	at io.gatling.core.action.ChainableAction.$bang(Action.scala:63)
	at io.gatling.core.action.ChainableAction.$bang$(Action.scala:61)
	at io.gatling.core.action.InnerLoop.$bang(Loop.scala:58)
	at io.gatling.core.action.Loop.execute(Loop.scala:54)
	at io.gatling.core.action.Action.$bang(Action.scala:38)
	at io.gatling.core.action.Action.$bang$(Action.scala:38)
	at io.gatling.core.action.Loop.$bang(Loop.scala:25)
	at io.gatling.core.controller.inject.Workload.startUser(Workload.scala:54)
	at io.gatling.core.controller.inject.Workload.$anonfun$injectUser$1(Workload.scala:63)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.rabbitmq.client.ShutdownSignalException: clean connection shutdown; protocol method: #method<connection.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:293)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:141)
	... 68 common frames omitted
21:00:59.798 [GatlingSystem-akka.actor.default-dispatcher-4] DEBUG io.gatling.core.action.Exit - End user #1
21:00:59.798 [GatlingSystem-akka.actor.default-dispatcher-4] DEBUG io.gatling.core.controller.inject.open.OpenWorkload - Start user #1
Parsing log file(s)...
21:00:59.808 [pool-1-thread-1] INFO io.gatling.charts.stats.LogFileReader - Collected ArrayBuffer(/Users/inenashev/Documents/Projects/amqp_vcrt/target/gatling/amqp-20200826180059444/simulation.log) from amqp-20200826180059444
21:00:59.814 [pool-1-thread-1] INFO io.gatling.charts.stats.LogFileReader - First pass
21:00:59.818 [pool-1-thread-1] INFO io.gatling.charts.stats.LogFileReader - First pass done: read 3 lines
21:00:59.824 [pool-1-thread-1] INFO io.gatling.charts.stats.LogFileReader - Second pass
21:00:59.836 [pool-1-thread-1] INFO io.gatling.charts.stats.LogFileReader - Second pass: read 3 lines
Parsing log file(s) done
Generating reports...`
is it me doing something wrong or I just misconfigured my script?

**Comment by red-bashmak** [comment]
It is so generic description of trouble, that i don't know what advice i can give to you. Possibly you pass not all parameters to scenario, that were declared. Need sources and more detailed description.
